# Generated by Django 3.1 on 2021-04-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210422_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='posts'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
